#macro ENTITIES global.entities
#macro PROJECTILES global.projectileManager
#macro SOUND global.soundManager
#macro GAME global.game
#macro WORLD global.world
#macro PARTICLES global.particleSystem
#macro VBUTTON global.vbutton
#macro LOG global.logger
#macro GAME_W 320
#macro GAME_H 240
#macro CURRENT_FRAME global.game.__current_frame
